server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/probook
    username: probook
    password: probook
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  basic:
    enabled: false